### ISSUE TITLE
Implementation guides links are broken

### ISSUE THREAD

**Issue by simonvadee** [arkhn/arkhn-ig-osiris#309]

**Comment by simonvadee** [comment]
@MaelleBaillet5 t'as check ?

**Comment by MaelleBaillet5** [comment]
J'ai vérifié les liens pour OSIRIS_MED. Voici ce qui ne fonctionne pas:
- lorsqu'on clique sur l'icone de RadiotherapyPlan, on arrive sur RadiotherapyCourse... et inversement pour RadiotherapyPlan. Je sais d'où vient l'erreur, je vais faire une PR pour le corriger.
- les 2 liens identifiés la dernière fois (modilité et technique) sur la page https://fhir.arkhn.com/osiris/StructureDefinition-modalityAndTechnique.html. Je corrige également.
