### ISSUE TITLE
Audit ModeleRadiotherapyOSIRIS

### ISSUE THREAD

**Issue by ummmaar** [arkhn/arkhn-ig-osiris#46]
Document de validation pour vérifier si l'IG est conforme au modèle OSIRIS "inital": [Modele Radiotherapy OSIRIS](https://github.com/arkhn/arkhn-ig-osiris/blob/us/doc/docs/ModeleRadiotherapyOSIRIS.pdf)

**Comment by Yasmine-Mrf** [comment]
[ModeleImagerieOSIRIS_fhir.pdf](https://github.com/arkhn/arkhn-ig-osiris/files/9798506/ModeleImagerieOSIRIS_fhir.pdf)
