### ISSUE TITLE
[RADIOMIC] Update IG 1.1

### ISSUE THREAD

**Issue by ummmaar** [arkhn/arkhn-ig-osiris#52]
**Source** : [ModeleRadiomiqueOSIRIS.pdf](https://github.com/siric-osiris/OSIRIS/blob/MED-OSIRIS/documentation/ModeleRadiomiqueOSIRIS.pdf)

**Comment by MaelleBaillet5** [comment]
Variable: softwareName

SD_RadiomicsCriteria:
- Add variables in extension
- Add statut: 1..1 (obligatory)
- Add description
- Add nomenclature IBSI: IBSI 61
- Add type of variable: string
- Add mapping

EX_RadiomicsCriteria:
- Add example for the variable
